feature: Implement basic UI with bottom nav bar and screens
AKushch1337/Bookish pull request #2
Opened 2023-06-01 19:41 UTC by AKushch1337

Implemented three screens with placeholder text and a bottom navigation bar using Jetpack Compose.

- For bottom navigation Compose Navigation was utilized. The NavHost and NavController components are used to manage the navigation stack and handle transitions between the newly added screens. Compose Navigation simplifies the navigation setup and allows for a seamless user experience.
- Sealed class was implemented to store information about the screens of our app
- A NavGraph was added to define flow and hierarchy of screens 

Screenshots: 

![image](https://github.com/AKushch1337/Bookish/assets/89732075/687aafb6-c0e3-4508-b13f-00840a47f17a)
![image](https://github.com/AKushch1337/Bookish/assets/89732075/2ef49e7a-99a7-44ff-b5c2-236f3b71143c)
![image](https://github.com/AKushch1337/Bookish/assets/89732075/b3da3785-0df1-4013-8b68-83bffeb3972b)

2023-06-03 13:03 UTC, neliudochka requested changes
- bad project structure: in composables directory, there are screens files. Extract them in a separate directory.
- optimize imports: delete unused imports
- use Preview functions for Composables.
Reason: Composable Previews give you the option to see the actual state of your composables without an emulator.

2023-06-03 13:03 UTC, neliudochka commented on app/src/main/java/com/example/bookish/composables/MainScreen.kt
> +@SuppressLint("UnusedMaterialScaffoldPaddingParameter")
- because of this suppression you may have problems with content representation: the bottom bar will suppress some part of the content and the user will never have access to it

2023-06-03 13:03 UTC, neliudochka commented on app/src/main/java/com/example/bookish/BottomBarScreen.kt
> +        title = "Library",
hardcoded text

2023-06-03 13:03 UTC, neliudochka commented on app/src/main/java/com/example/bookish/BottomBarScreen.kt
> +        title = "Lists",
hardcoded text

2023-06-03 13:03 UTC, neliudochka commented on app/src/main/java/com/example/bookish/BottomBarScreen.kt
> +        title = "Setting",
hardcoded text

2023-06-03 13:03 UTC, neliudochka commented on app/src/main/java/com/example/bookish/composables/Lists.kt
> +            text = "Lists",
hardcoded text

2023-06-03 13:03 UTC, neliudochka commented on app/src/main/java/com/example/bookish/composables/MainScreen.kt
> +            Icon(imageVector = screen.icon, contentDescription = "NavigationIcon")
hardcoded text

2023-06-03 22:58 UTC, AKushch1337 commented
> * use Preview functions for Composables.
>   Reason: Composable Previews give you the option to see the actual state of your composables without an emulator.

Thanks for the tip. Will use them more later in dev cycle, no need to add them for now

Other than that all fixed, thanks for the review, my dear!

2023-06-03 22:59 UTC, AKushch1337 commented
> * use Preview functions for Composables.
>   Reason: Composable Previews give you the option to see the actual state of your composables without an emulator.

Thanks for the tip. Will use them more later in dev cycle, no need to add them for now

Other than that all fixed, thanks for the review, my dear!

2023-06-03 23:01 UTC, merged

2023-06-03 23:02 UTC, AKushch1337 commented
> * use Preview functions for Composables.
>   Reason: Composable Previews give you the option to see the actual state of your composables without an emulator.

Thanks for the tip. Will use them more later in dev cycle, no need to add them for now

Other than that all fixed, thanks for the review, my dear!

2023-06-04 22:28 UTC, neliudochka commented
![image](https://github.com/AKushch1337/Bookish/assets/90915275/34e9825e-8922-4adc-a9bb-61c7c40d5cbc)

2023-06-04 22:35 UTC, AKushch1337 commented
- https://github.com/AKushch1337/Bookish/assets/89732075/1c32081f-01bd-4f1c-8d99-8384dc3ded81