feature: Ability to see PDF files from your local storage
AKushch1337/Bookish pull request #9
Opened 2023-06-07 20:09 UTC by AKushch1337

- Used [Bouquet](https://github.com/GRizzi91/bouquet) framework for easier showcase of PDF files
- Added floating action button to choose which file to show on the screen
- In the pdf file u can see on which page you currently are

## Screenshots
<img src="https://github.com/AKushch1337/Bookish/assets/89732075/765add27-c460-4dbe-b861-6ad50191a62f" width=50% height=50%>

<img src="https://github.com/AKushch1337/Bookish/assets/89732075/3283cf35-ee74-421c-b4cf-5bc2b237dba0" width=50% height=50%>

<img src="https://github.com/AKushch1337/Bookish/assets/89732075/2ac83de4-62a5-4834-a3e3-dfd24751ef22" width=50% height=50%>

2023-06-07 23:05 UTC, neliudochka requested changes
- Make viewing the PDF file on a separate page and not right on the library screen
-  While reading the file the BottomNavBar is too distracting. Hide it or make it not so bright
- You haven't finished physics lab.
Problem: "треба розрахувати довірчий інтервал для величин x та h для всіх випадків їх вимірювання при довірчий ймовірності 0,9. Оптична різниця ходу - різниця ходу з урахуванням оптичних властивостей середовища". 
Будь ласка, не показуйте недороблені лаби адептам Скирти.

2023-06-07 23:05 UTC, neliudochka commented on app/src/main/java/com/example/bookish/composables/pdfview/DocumentPicker.kt
> +import android.net.Uri
You lost the package name. Find it and add

2023-06-07 23:11 UTC, AKushch1337 commented on app/src/main/java/com/example/bookish/composables/pdfview/DocumentPicker.kt
> +import android.net.Uri
Will do

2023-06-08 02:48 UTC, AKushch1337 commented
Will close this as the deadline is closer and closer. Thanks for the review anyways

2023-06-08 02:48 UTC, merged